package ch8;

public class ExceptionEx11 {
    public static void main(String[] args) {
        throw new RuntimeException(); //성공적으로 컴파일 되지만 프로그램이 비정상 종료됨
    }
}
